### ISSUE TITLE
Compiling create_products_table

### ISSUE THREAD

**Issue by giuliagrfo** [Yuri-Punzo/team-branch#11]
Creiamo la tabella nel metodo up()
Schema::create('projects', function (Blueprint $table) {
            $table->id();
            $table->string('title', 100)->unique();
            $table->string('slug');
            $table->text('description')->nullable();
            $table->timestamps();
        });

**Comment by sgraziola** [comment]
ci penso io

**Comment by sgraziola** [comment]
ciao

**Comment by Yuri-Punzo** [comment]
Giulia hai ricevuto la mail ?

**Comment by sgraziola** [comment]
Ciao fatto tutto. Chiudo
